mybatis-flex:
  datasource:
    w5-ds1:
      url: jdbc:h2:file:E:/wl/db/w5-ds1-local
      username:
      password:
    w5-ds2:
      url: jdbc:h2:file:E:/wl/db/w5-ds2-local
      username:
      password:

w5:
  admin:
    name: w5-local
    password: pwd-local